name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.12.2
      - run: npm install
      # - run: npm test
      - run: npm install -g vsce
      - run: vsce package
      - run: vsce publish -p ${{ secrets.VSCE_PAT }}
